[package]
name = "wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.3"
env_logger  = "0.9.1"
wgpu = "0.13.1"
log = "0.4.17"
pollster = "0.2"
rand = "0.8.5"
